### ISSUE TITLE
Setup Instructions Needed

### ISSUE THREAD

**Issue by phere-x** [Dester-Lib/Dester-Lib-Server#2]
I even tried following this guide but it only used Heroku for everything. https://telegra.ph/IsThisGuide-02-12

But I kept ending up with "cannot connect to Backend - 503 error" even though backend had successfully deplyed.

**Comment by AlkenD** [comment]
> I even tried following this guide but it only used Heroku for everything. https://telegra.ph/IsThisGuide-02-12
> 
> But I kept ending up with "cannot connect to Backend - 503 error" even though backend had successfully deplyed.

I recommend checking tg group

**Comment by phere-x** [comment]
Can I get a invite?

**Comment by AlkenD** [comment]
> Can I get a invite?

Here you go https://t.me/DesterLib
